AddUser function

diff --git a/User Manager/ShowMenu b/User Manager/ShowMenu
--- a/User Manager/ShowMenu
+++ b/User Manager/ShowMenu
@@ -11,14 +11,14 @@ function ShowMenu
 	do
 		echo " "
 		echo "    ***************************************************************"
-		echo "    *                	       Users Manager 						*"
+		echo "    * 						Users Manager 						*"
 		echo "    ***************************************************************"
-		echo "    *           1- Create Single User        				        *"
-		echo "    *           2- Create Multiple Users 						    *"
-		echo "    *           3- Delete Users 								    *"
-		echo "    *           4- Show Users 				                    *"
-		echo "    *           5- Manage Passwords 				                *"
-		echo "    *           6- Return                                         *"
+		echo "    * 		1- Create Single User 								*"
+		echo "    * 		2- Create Multiple Users 							*"
+		echo "    * 		3- Delete Users 									*"
+		echo "    * 		4- Show Users 										*"
+		echo "    * 		5- Manage Passwords 								*"
+		echo "    * 		6- Return 											*"
 		echo "    ***************************************************************"
 		echo " "
 		echo -n "Choose an option : "
@@ -76,6 +76,43 @@ done
 }
 
 # Add Single User
+function AddUser
+{
+	clear
+	echo "" > usr
+	login=""
+	nbre=0
+	while [ -z $login ] || [ $nbre = 0 ]
+	do
+		clear
+		echo " "
+		read -p "Login : " login
+		s=${login:0:1}
+		echo "$s" > usr
+		nbre=`grep -c "^[a-zA-Z]" usr`
+	done 
+	UserExists "$login" 
+	if [ "$?" -eq 0 ]; then 
+		echo "User exists. Please try with another name !!"
+		sleep 2
+		AddUser
+	else
+		ListGroups
+		read -p " Choose Group : " group
+		read -s -p "Password :" password
+		useradd -p "$password" -g "$group" "$login" >> /dev/null 2<&1
+		operation=$?
+		echo "$operation"
+		if [ "$operation" -eq 0 ]; then 
+			echo "User was added successefully !!"
+			sleep 2
+			ShowMenu
+		else echo "An Error was occured !!"
+			sleep 2
+			ShowMenu
+		fi
+	fi
+}
 
 # Add Multiple Users
 
